version: '3'

services:
  redis:
    image: redis:5.0
    volumes:
      - ./volumes/redis:/data
    ports:
      - "16379:6379"
  rqmonitor:
    image: pranavgupta1234/rqmonitor
    environment:
      RQ_MONITOR_REDIS_URL: redis://redis:6379
      RQ_MONITOR_DEBUG: 1
    ports:
      - "8899:8899"
