version: '3'

services:
  redis:
    image: redis:5.0
    volumes:
      - ./volumes/redis:/data
    ports:
      - "16379:6379"
  rqdash:
    image: eoranged/rq-dashboard
    environment:
      RQ_DASHBOARD_REDIS_URL: redis://redis:16379/9
      RQ_DASHBOARD_USERNAME: rq
      RQ_DASHBOARD_PASSWORD: rq
    ports:
      - "9181:9181"
    restart: "no"
    stop_grace_period: 2s
