# Generated by Django 3.2.6 on 2021-12-14 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='last_query',
        ),
        migrations.AddField(
            model_name='connection',
            name='offline_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Disconnect timestamp'),
        ),
        migrations.AddField(
            model_name='connection',
            name='online_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Connection timestamp'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='last_action',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last action'),
        ),
    ]
