name: Build wheels

on:
  release:
    types: [published, edited]
  push:
    branches: [main]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3

      - name: Install
        run: python -m pip install build

      - name: Build wheels
        run: python -m build .

      - uses: actions/upload-artifact@v4
        with:
          name: Wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: dist/*.whl
